### PR TITLE
Support TSD

### PR DESCRIPTION
**Pull request by jonjaques**
Hello and thank you for putting this together. 

I added a few things such as a package.json, and tsd.json inside the example folder, so you can cd into example and build it right away.

One thing I noticed in my own project right away was that either webpack or tsc is not following references declared more than one file deep. I believe this should definitely be supported for bigger projects.

I intend to dig into this more, but I wanted to send this over to get your feedback (or pointers :) ).

Edit: I mistakenly assumed NPM would recurse into all directories with package.json and install them, but apparently that is not the case. So install requires `npm install && cd example && npm install` which is ridiculous IMO, separate issue.

### CODE REVIEW

**Comment by andreypopp** [comment]
Thanks!

**Comment by jgoz** [comment]
Hmm, this PR broke the compile operation for me:

``` sh
SyntaxTreeCache.Initialize: new HostCache: 0
SyntaxTreeCache.Initialize: createSourceFile: 0
SyntaxTreeCache.Initialize: fixupParentRefs : 0
Hash: 8725a759547b603a4e0b
Version: webpack 1.5.1
Time: 483ms
                                                     Asset  Size  Chunks             Chunk Names
    /.../typescript-loader/example/bundle.js  1792       0  [emitted]  main
/.../typescript-loader/example/bundle.js.map  1896       0  [emitted]  main
   [0] ./index.ts 260 {0} [built] [2 errors]

ERROR in ./index.ts
File '/.../typescript-loader/example/node_modules/react/addons.js' must have extension '.ts' or '.d.ts'.

ERROR in ./index.ts
/.../typescript-loader/example/index.ts (5, 24) Cannot find external module 'react/addons'.
```

I think it's because the dependency graph of `tsd.d.ts` is not being analyzed. I suspect this will be a fairly common scenario in larger codebases, so it should be addressed.

**Comment by andreypopp** [comment]
Yes, this is the thing @jonjaques noticed:

> One thing I noticed in my own project right away was that either webpack or tsc is not following references declared more than one file deep. I believe this should definitely be supported for bigger projects.

I'll push the fix shortly.

**Comment by jgoz** [comment]
Whoops, I didn't read the original PR closely enough. Thanks!

**Comment by andreypopp** [comment]
a3d44c9 addresses this

**Comment by jgoz** [comment]
:+1:

**Comment by jonjaques** [comment]
Thanks a bunch guys!

**Pull request merged**
